before_script:
    - pip install pytest -i https://pypi.douban.com/simple

whoami:
    script:
        - whoami

# https://stackoverflow.com/questions/38723788/how-to-run-python-unit-tests-with-xml-output
JUnit:
    stage: test
    script:
        - py.test --junitxml=rspec.xml test/test_widget.py
    artifacts:
        paths:
            - rspec.xml
        reports:
            junit: rspec.xml
