before_script:
    - apt update
    - apt install -y python3
    - apt install -y python3-pip
    - pip3 install pytest -i https://pypi.douban.com/simple

whoami:
    script:
        - whoami

JUnit:
    stage: test
    script:
        - py.test --junitxml=rspec.xml test/test_widget.py
    artifacts:
        paths:
            - rspec.xml
        reports:
            junit: rspec.xml
